name: test
on:
  push:
    branches:
    - 'main'
  pull_request:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node: [18, 'lts/*']
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: npm ci
        run: |
          npm ci

      - name: test
        run: npm run test
